[build]
  publish = "public"
  # This command generates the public/env-config.js file with Firebase credentials
  # It uses printf for a more robust way to include environment variables.
  command = "printf 'window.FIREBASE_CONFIG = {\\n  apiKey: \\'%s\\',\\n  authDomain: \\'%s\\',\\n  projectId: \\'%s\\',\\n  storageBucket: \\'%s\\',\\n  messagingSenderId: \\'%s\\',\\n  appId: \\'%s\\',\\n  measurementId: \\'%s\\'\\n};' \"$FIREBASE_API_KEY\" \"$FIREBASE_AUTH_DOMAIN\" \"$FIREBASE_PROJECT_ID\" \"$FIREBASE_STORAGE_BUCKET\" \"$FIREBASE_MESSAGING_SENDER_ID\" \"$FIREBASE_APP_ID\" \"$FIREBASE_MEASUREMENT_ID\" > ./public/env-config.js"

[context.production.environment]
  # These are declarations for Netlify environment variables.
  # Their ACTUAL values MUST be set in the Netlify UI.
  FIREBASE_API_KEY = ""
  FIREBASE_AUTH_DOMAIN = ""
  FIREBASE_PROJECT_ID = ""
  FIREBASE_STORAGE_BUCKET = ""
  FIREBASE_MESSAGING_SENDER_ID = ""
  FIREBASE_APP_ID = ""
  FIREBASE_MEASUREMENT_ID = ""