[build]
  publish = "public"
  # No explicit command needed here for env var injection with this HTML setup.
  # Netlify will automatically perform string replacement on %VITE_VAR% placeholders.

[context.production.environment]
  # These variables will be made available during the build process
  # and automatically injected into your HTML if referenced correctly.
  VITE_FIREBASE_API_KEY = ""
  VITE_FIREBASE_AUTH_DOMAIN = ""
  VITE_FIREBASE_PROJECT_ID = ""
  VITE_FIREBASE_STORAGE_BUCKET = ""
  VITE_FIREBASE_MESSAGING_SENDER_ID = ""
  VITE_FIREBASE_APP_ID = ""
  VITE_FIREBASE_MEASUREMENT_ID = ""