[build]
  publish = "public"
  # This command explicitly creates 'public/firebase-init.js' during the build
  # and injects the Firebase environment variables into it.
  command = """
    echo "const firebaseConfig = {" > ./public/firebase-init.js
    echo "  apiKey: \"$VITE_FIREBASE_API_KEY\"," >> ./public/firebase-init.js
    echo "  authDomain: \"$VITE_FIREBASE_AUTH_DOMAIN\"," >> ./public/firebase-init.js
    echo "  projectId: \"$VITE_FIREBASE_PROJECT_ID\"," >> ./public/firebase-init.js
    echo "  storageBucket: \"$VITE_FIREBASE_STORAGE_BUCKET\"," >> ./public/firebase-init.js
    echo "  messagingSenderId: \"$VITE_FIREBASE_MESSAGING_SENDER_ID\"," >> ./public/firebase-init.js
    echo "  appId: \"$VITE_FIREBASE_APP_ID\"," >> ./public/firebase-init.js
    echo "  measurementId: \"$VITE_FIREBASE_MEASUREMENT_ID\"" >> ./public/firebase-init.js
    echo "};" >> ./public/firebase-init.js
    echo "export { firebaseConfig };" >> ./public/firebase-init.js
  """

[context.production.environment]
  # These environment variables must be set in the Netlify UI.
  # The values here are placeholders only for the TOML syntax.
  VITE_FIREBASE_API_KEY = ""
  VITE_FIREBASE_AUTH_DOMAIN = ""
  VITE_FIREBASE_PROJECT_ID = ""
  VITE_FIREBASE_STORAGE_BUCKET = ""
  VITE_FIREBASE_MESSAGING_SENDER_ID = ""
  VITE_FIREBASE_APP_ID = ""
  VITE_FIREBASE_MEASUREMENT_ID = ""