[build]
  publish = "public"
  # This command runs before deployment to generate the env-config.js file
  # It dynamically creates the window.FIREBASE_CONFIG object using your Netlify environment variables.
  command = """
    echo "window.FIREBASE_CONFIG = {" > ./public/env-config.js
    echo "  apiKey: '${FIREBASE_API_KEY}'," >> ./public/env-config.js
    echo "  authDomain: '${FIREBASE_AUTH_DOMAIN}'," >> ./public/env-config.js
    echo "  projectId: '${FIREBASE_PROJECT_ID}'," >> ./public/env-config.js
    echo "  storageBucket: '${FIREBASE_STORAGE_BUCKET}'," >> ./public/env-config.js
    echo "  messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}'," >> ./public/env-config.js
    echo "  appId: '${FIREBASE_APP_ID}'," >> ./public/env-config.js
    echo "  measurementId: '${FIREBASE_MEASUREMENT_ID}'" >> ./public/env-config.js
    echo "};" >> ./public/env-config.js
  """

[context.production.environment]
  # These variables will be provided by Netlify to the build command above.
  # You MUST set their actual values in the Netlify UI (next step).
  FIREBASE_API_KEY = ""
  FIREBASE_AUTH_DOMAIN = ""
  FIREBASE_PROJECT_ID = ""
  FIREBASE_STORAGE_BUCKET = ""
  FIREBASE_MESSAGING_SENDER_ID = ""
  FIREBASE_APP_ID = ""
  FIREBASE_MEASUREMENT_ID = ""